# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: LWAPI/LWAPI.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  # Path to LWAPIBindingGenerator.exe
  LWAPI_BINDING_GENERATOR_DIR: C:/LWAPIBindingGenerator

  # Path to VS2010 tools
  VS100COMNTOOLS: C:/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools/

  # Path to DX9 SDK
  DXSDK_DIR: C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download and install Visual C++ Express 2010 headers
      run: |
        Invoke-WebRequest -URI https://dl.dropbox.com/s/az782o7gr5lr3o3/include.zip -OutFile "include.zip"
        mkdir "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/Include"
        Expand-Archive -Path "include.zip" -DestinationPath "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/Include"
        Invoke-WebRequest -URI https://dl.dropbox.com/s/zu1bl7zj0jwzvtb/include2.zip -OutFile "include2.zip"
        mkdir "C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/include"
        Expand-Archive -Path "include2.zip" -DestinationPath "C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/include"
        Invoke-WebRequest -URI https://dl.dropbox.com/s/vh6eipm5psfwmp7/include3.zip -OutFile "include3.zip"
        mkdir "C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Include"
        Expand-Archive -Path "include3.zip" -DestinationPath "C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Include"

    - uses: actions/checkout@v3

    - name: Download latest release of LWAPIBindingGenerator
      run: |
        mkdir "${{env.LWAPI_BINDING_GENERATOR_DIR}}"
        gh release download --repo Radfordhound/LWAPIBindingGenerator --pattern "*.exe" --dir "${{env.LWAPI_BINDING_GENERATOR_DIR}}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v3
      with:
        name: LWAPI
        path: ${{env.GITHUB_WORKSPACE}}/LWAPI/bin/Release/
